module.exports = {
  INPUT_DIR: '',
  INPUT_FILE_REVIEWS: '',
  INPUT_FILE_REVIEW_PHOTOS: '',
  INPUT_FILE_CHARACTERISTICS: '',
  INPUT_FILE_CHARACTERISTICS_REVIEWS: '',

  TRANSFORM_OUTPUT_DIR: '',
  TRANSFORM_OUTPUT_FILE_REVIEWS: `processed-${Date.now()}.csv`,
};
